from dash import Dash, page_registry, page_container, html, dcc
import dash_bootstrap_components as dbc
"""
- Kill the app with `ctrl+c` not `ctrl+z` as z does not release port.
- Mandatory to use absolute aiqc imports, not relative: `aiqc.orm` not `..orm`.
- Stopped using jupyter_dash when they removed `_terminate_server_for_port`
  It wasn't reliable: hung ports with leaks, silent failures.

- "External css/js files are loaded before the `/assets`."
- "CSS/JS files in `/assets` are auto served." Don't need to be added as externals.
- BOOTSTRAP points to remote cdn: https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css
"""
sheets    = [dbc.themes.BOOTSTRAP]
app       = Dash(
    __name__
    , external_stylesheets         = sheets
    , update_title                 = "♻️"
    , title                        = "AIQC"
    , suppress_callback_exceptions = True
    , use_pages                    = True
)
# Mandatory when using components that are generated by other callbacks
# app.config['suppress_callback_exceptions'] = True

# `app.update_title` can only be set when instantiating the app.

### puting this here just to get it running 
refresh_seconds = 10*1000


app.layout = html.Div(
    [
        # Navbar
        html.Div(
            [
                # Logo
                html.Div(
                    html.A(
                        html.Img(src="assets/logo_wide_small.svg", height="35px"),
                        href="https://aiqc.io",
                    ),
                    className='logo'
                ),
                # Links
                html.Div(
                    [
                        html.Div(
                            dcc.Link(
                                f"{page['name']}",
                                href=page["relative_path"], 
                                className="linx"
                            ),
                            className="linx-box"
                        )
                        for page in page_registry.values()
                    ],
                    className="all-linx"
                ),         
            ],
            className='navig'
        ),
        # This holds the multi-page content
        page_container
    ]
)

if __name__ == '__main__':
    app.run_server(debug=True, port='9992')
